# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jonataswalker/www/projetos/LifeSimulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jonataswalker/www/projetos/LifeSimulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jonataswalker/www/projetos/LifeSimulator/CMakeFiles /Users/jonataswalker/www/projetos/LifeSimulator//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jonataswalker/www/projetos/LifeSimulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LifeSimulator

# Build rule for target.
LifeSimulator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LifeSimulator
.PHONY : LifeSimulator

# fast build rule for target.
LifeSimulator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LifeSimulator.dir/build.make CMakeFiles/LifeSimulator.dir/build
.PHONY : LifeSimulator/fast

src/Climate.o: src/Climate.cpp.o
.PHONY : src/Climate.o

# target to build an object file
src/Climate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LifeSimulator.dir/build.make CMakeFiles/LifeSimulator.dir/src/Climate.cpp.o
.PHONY : src/Climate.cpp.o

src/Climate.i: src/Climate.cpp.i
.PHONY : src/Climate.i

# target to preprocess a source file
src/Climate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LifeSimulator.dir/build.make CMakeFiles/LifeSimulator.dir/src/Climate.cpp.i
.PHONY : src/Climate.cpp.i

src/Climate.s: src/Climate.cpp.s
.PHONY : src/Climate.s

# target to generate assembly for a file
src/Climate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LifeSimulator.dir/build.make CMakeFiles/LifeSimulator.dir/src/Climate.cpp.s
.PHONY : src/Climate.cpp.s

src/DNA.o: src/DNA.cpp.o
.PHONY : src/DNA.o

# target to build an object file
src/DNA.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LifeSimulator.dir/build.make CMakeFiles/LifeSimulator.dir/src/DNA.cpp.o
.PHONY : src/DNA.cpp.o

src/DNA.i: src/DNA.cpp.i
.PHONY : src/DNA.i

# target to preprocess a source file
src/DNA.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LifeSimulator.dir/build.make CMakeFiles/LifeSimulator.dir/src/DNA.cpp.i
.PHONY : src/DNA.cpp.i

src/DNA.s: src/DNA.cpp.s
.PHONY : src/DNA.s

# target to generate assembly for a file
src/DNA.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LifeSimulator.dir/build.make CMakeFiles/LifeSimulator.dir/src/DNA.cpp.s
.PHONY : src/DNA.cpp.s

src/LogManager.o: src/LogManager.cpp.o
.PHONY : src/LogManager.o

# target to build an object file
src/LogManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LifeSimulator.dir/build.make CMakeFiles/LifeSimulator.dir/src/LogManager.cpp.o
.PHONY : src/LogManager.cpp.o

src/LogManager.i: src/LogManager.cpp.i
.PHONY : src/LogManager.i

# target to preprocess a source file
src/LogManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LifeSimulator.dir/build.make CMakeFiles/LifeSimulator.dir/src/LogManager.cpp.i
.PHONY : src/LogManager.cpp.i

src/LogManager.s: src/LogManager.cpp.s
.PHONY : src/LogManager.s

# target to generate assembly for a file
src/LogManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LifeSimulator.dir/build.make CMakeFiles/LifeSimulator.dir/src/LogManager.cpp.s
.PHONY : src/LogManager.cpp.s

src/Map.o: src/Map.cpp.o
.PHONY : src/Map.o

# target to build an object file
src/Map.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LifeSimulator.dir/build.make CMakeFiles/LifeSimulator.dir/src/Map.cpp.o
.PHONY : src/Map.cpp.o

src/Map.i: src/Map.cpp.i
.PHONY : src/Map.i

# target to preprocess a source file
src/Map.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LifeSimulator.dir/build.make CMakeFiles/LifeSimulator.dir/src/Map.cpp.i
.PHONY : src/Map.cpp.i

src/Map.s: src/Map.cpp.s
.PHONY : src/Map.s

# target to generate assembly for a file
src/Map.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LifeSimulator.dir/build.make CMakeFiles/LifeSimulator.dir/src/Map.cpp.s
.PHONY : src/Map.cpp.s

src/SolarCycle.o: src/SolarCycle.cpp.o
.PHONY : src/SolarCycle.o

# target to build an object file
src/SolarCycle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LifeSimulator.dir/build.make CMakeFiles/LifeSimulator.dir/src/SolarCycle.cpp.o
.PHONY : src/SolarCycle.cpp.o

src/SolarCycle.i: src/SolarCycle.cpp.i
.PHONY : src/SolarCycle.i

# target to preprocess a source file
src/SolarCycle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LifeSimulator.dir/build.make CMakeFiles/LifeSimulator.dir/src/SolarCycle.cpp.i
.PHONY : src/SolarCycle.cpp.i

src/SolarCycle.s: src/SolarCycle.cpp.s
.PHONY : src/SolarCycle.s

# target to generate assembly for a file
src/SolarCycle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LifeSimulator.dir/build.make CMakeFiles/LifeSimulator.dir/src/SolarCycle.cpp.s
.PHONY : src/SolarCycle.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LifeSimulator.dir/build.make CMakeFiles/LifeSimulator.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LifeSimulator.dir/build.make CMakeFiles/LifeSimulator.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LifeSimulator.dir/build.make CMakeFiles/LifeSimulator.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... LifeSimulator"
	@echo "... src/Climate.o"
	@echo "... src/Climate.i"
	@echo "... src/Climate.s"
	@echo "... src/DNA.o"
	@echo "... src/DNA.i"
	@echo "... src/DNA.s"
	@echo "... src/LogManager.o"
	@echo "... src/LogManager.i"
	@echo "... src/LogManager.s"
	@echo "... src/Map.o"
	@echo "... src/Map.i"
	@echo "... src/Map.s"
	@echo "... src/SolarCycle.o"
	@echo "... src/SolarCycle.i"
	@echo "... src/SolarCycle.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

